/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetcarafe_hoby;

import com.sun.org.apache.bcel.internal.generic.BREAKPOINT;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import jdk.nashorn.internal.ir.BreakNode;



/**
 *
 * @author Miandrisoa Hoby
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    int valC1, valC2;
    public Main() {
        initComponents();
        txt_mvt1.setVisible(false);
        txt_mvt2.setVisible(false);
        reussi.setVisible(false);
        btn_remplir1.setVisible(false);
        btn_remplir2.setVisible(false);
        btn_Vider1.setVisible(false);
        btn_Vider2.setVisible(false);
        btn_t1vers2.setVisible(false);
        btn_T2vers1.setVisible(false);
       
        icon_reussi.setVisible(false);
        //carafe3_gallon.setEnabled(false);
        //carafe4_gallon.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        carafe3_gallon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        carafe4_gallon = new javax.swing.JTextField();
        carafe_2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        carafe_1 = new javax.swing.JProgressBar();
        reussi = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nbEntrer_2 = new javax.swing.JTextField();
        nb_result = new javax.swing.JTextField();
        nbEntrer_1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_mvt1 = new javax.swing.JLabel();
        btn_Vider1 = new javax.swing.JButton();
        btn_remplir2 = new javax.swing.JButton();
        btn_remplir1 = new javax.swing.JButton();
        btn_Vider2 = new javax.swing.JButton();
        btn_T2vers1 = new javax.swing.JButton();
        btn_t1vers2 = new javax.swing.JButton();
        btn_taille = new javax.swing.JToggleButton();
        txt_mvt2 = new javax.swing.JLabel();
        icon_reussi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(320, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(702, 363));
        jPanel1.setPreferredSize(new java.awt.Dimension(702, 363));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carafe3_gallon.setEditable(false);
        carafe3_gallon.setBackground(new java.awt.Color(255, 255, 255));
        carafe3_gallon.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        carafe3_gallon.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(carafe3_gallon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 40, 30));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Carafe N°2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, 20));

        carafe4_gallon.setEditable(false);
        carafe4_gallon.setBackground(new java.awt.Color(255, 255, 255));
        carafe4_gallon.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        carafe4_gallon.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(carafe4_gallon, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 40, 30));

        carafe_2.setForeground(new java.awt.Color(0, 51, 255));
        carafe_2.setMaximum(4);
        carafe_2.setOrientation(1);
        carafe_2.setString("0 Gallon");
        carafe_2.setStringPainted(true);
        jPanel1.add(carafe_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 176, 90, 80));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("Carafe N°1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        carafe_1.setForeground(new java.awt.Color(0, 51, 255));
        carafe_1.setMaximum(3);
        carafe_1.setOrientation(1);
        carafe_1.setToolTipText("");
        carafe_1.setString("0 Gallon");
        carafe_1.setStringPainted(true);
        jPanel1.add(carafe_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 197, 90, 60));

        reussi.setBackground(new java.awt.Color(255, 255, 51));
        reussi.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        reussi.setForeground(new java.awt.Color(0, 204, 255));
        reussi.setText("Opération réussi :) ");
        jPanel1.add(reussi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 600, 20));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-jouer-30.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 60, 30));

        nbEntrer_2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nbEntrer_2.setForeground(new java.awt.Color(0, 0, 255));
        nbEntrer_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nbEntrer_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbEntrer_2ActionPerformed(evt);
            }
        });
        jPanel1.add(nbEntrer_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 40, 30));

        nb_result.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nb_result.setForeground(new java.awt.Color(0, 0, 255));
        nb_result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(nb_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 30));

        nbEntrer_1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nbEntrer_1.setForeground(new java.awt.Color(0, 0, 255));
        nbEntrer_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nbEntrer_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbEntrer_1ActionPerformed(evt);
            }
        });
        jPanel1.add(nbEntrer_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 40, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("C2 :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("ResultatC1 :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("C1 :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt_mvt1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        txt_mvt1.setForeground(new java.awt.Color(0, 153, 153));
        txt_mvt1.setText("remplir Carafe N°1");
        jPanel1.add(txt_mvt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 430, 20));

        btn_Vider1.setText("Vider1");
        btn_Vider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Vider1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Vider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        btn_remplir2.setText("remplir2");
        btn_remplir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remplir2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remplir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        btn_remplir1.setText("remplir1");
        btn_remplir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remplir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remplir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        btn_Vider2.setText("Vider2");
        btn_Vider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Vider2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Vider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        btn_T2vers1.setText("Trans2vers1");
        btn_T2vers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_T2vers1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_T2vers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        btn_t1vers2.setText("Trans1vers2");
        btn_t1vers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_t1vers2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_t1vers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        btn_taille.setBackground(new java.awt.Color(255, 255, 255));
        btn_taille.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_taille.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetcarafe_hoby/icons8-taille-crayon-25.png"))); // NOI18N
        btn_taille.setText("Taille");
        btn_taille.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_taille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tailleActionPerformed(evt);
            }
        });
        jPanel1.add(btn_taille, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 30));

        txt_mvt2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        txt_mvt2.setForeground(new java.awt.Color(0, 153, 153));
        txt_mvt2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_mvt2.setText("jLabel6");
        jPanel1.add(txt_mvt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 470, 20));

        icon_reussi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-test-partiellement-réussi-48.png"))); // NOI18N
        jPanel1.add(icon_reussi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/empty-glass-carafe-water-stand-white-background-isolated-167418694.jpg"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void affichage(){
        int nbC1 = carafe_1.getValue();
        int nbC2 = carafe_2.getValue(); 
        JOptionPane.showMessageDialog(null, "C1="+nbC1);
        JOptionPane.showMessageDialog(null, "C2="+nbC2);
    }
    //Remplissage gallons
      public void remplirC1(){
          icon_reussi.setVisible(false);
          txt_mvt1.setText("Remplir Carafe N°1");
          txt_mvt2.setText("");
          valC1 = Integer.parseInt(nbEntrer_1.getText());
          carafe_1.setValue(10);
          carafe_1.setString(valC1+"Gallons");
      }
      public void remplirC2(){
          icon_reussi.setVisible(false);
          txt_mvt2.setText("Remplir Carafe N°2");
          txt_mvt1.setText("");
          valC2 = Integer.parseInt(nbEntrer_2.getText());
          carafe_2.setValue(10);
          carafe_2.setString(valC2+"Gallons");
      }
//Vidage des gallons
      public void viderC1(){
          icon_reussi.setVisible(false);
          txt_mvt1.setText("Vider Carafe N°1");
          txt_mvt2.setText("");
          carafe_1.setValue(0);
          carafe_1.setString("0 Gallon");
      }
      public void viderC2(){
          icon_reussi.setVisible(false);
          txt_mvt2.setText("Vider Carafe N°2");
          txt_mvt1.setText("");
          carafe_2.setValue(0);
          carafe_2.setString("0 Gallon");
      }
      public void C1versC2(){
          icon_reussi.setVisible(false);
          txt_mvt1.setText("Transverser le contenu du Carafe N°1 vers N°2");
          txt_mvt2.setText("");
          valC1 = Integer.parseInt(nbEntrer_1.getText());
          valC2 = Integer.parseInt(nbEntrer_2.getText());
          int nbC1 = carafe_1.getValue();
          int nbC2 = carafe_2.getValue();
          //JOptionPane.showMessageDialog(this, "C1="+nbC1);
          //JOptionPane.showMessageDialog(this, "C2="+nbC2);
            if(nbC1==0){
              JOptionPane.showMessageDialog(null, "Opération non valide,carafe vide");
            }
            else if (valC2>=valC1 && nbC2<nbC1 && nbC1==valC1 && nbC2==0)//maxcarafe1<maxcarafe2 et contenuCarafe2<contenuCarafe1 et contenuCarafe1=maxcarafe1
            {
                carafe_2.setValue(nbC1);
                carafe_2.setString(valC1 + "Gallons");
                nbC2=carafe_2.getValue();
                //JOptionPane.showMessageDialog(null,"nbC2= "+ nbC2);
                carafe_1.setValue(0);
                carafe_1.setString("0Gallon");
            }
            else if(valC2>=valC1 && nbC2>0 && nbC2<=nbC1)//maxcarafe1<maxcarafe2 et 0 < contenuCarafe2 <=contenuCarafe1
            {
                //JOptionPane.showMessageDialog(null, "else if");22
                carafe_2.setValue(nbC1+nbC2);
                
                carafe_2.setString(valC2+"Gallons");
                int s= valC1-(valC2-nbC2);
                carafe_1.setValue(s);
                carafe_1.setString(s+"Gallons");
                nbC2 = carafe_2.getValue();
                //JOptionPane.showMessageDialog(null, "nbC2="+nbC2);
            }
            
            else if(valC2>=valC1 && nbC2==valC2 && nbC1>=0)//maxcarafe1<maxcarafe2 et contenuCarafe2=maxCarafe2 et contenuCarafe1 >= 0
            {
                //JOptionPane.showMessageDialog(null, "Si Caraffe 1>=0 et caraffe 2 =max carafe 2 ");
                carafe_2.setValue(valC2);
                carafe_2.setString(valC2+"Gallons");
                nbC2 = carafe_2.getValue();
                //JOptionPane.showMessageDialog(null, "nbC2="+nbC2);
            }
            else if(valC2>=valC1 && nbC2==0 && nbC1>0 && nbC1<valC1){//maxcarafe1<maxcarafe2 et contenuCarafe2=0 et maxcarafe1>contenuCarafe1 >0 
                //JOptionPane.showMessageDialog(null, "Si Caraffe 1>=0 et caraffe 2 =0 ");
                carafe_2.setValue(nbC1);
                nbC2=carafe_2.getValue();
                carafe_2.setString(nbC2+"Gallons");
                carafe_1.setValue(0);
                carafe_1.setString("OGallon");
                nbC2 = carafe_2.getValue();
                //JOptionPane.showMessageDialog(null, "nbC2="+nbC2);
                }
            else if(nbC2>0 && valC2>=valC1 && nbC1>=nbC2){// (3,2) ou (2,1) ou (3,3) ou (2,2)ou (1,1) ou (3,1)
                //JOptionPane.showMessageDialog(null, "nbC2>0 && valC2>=valC1 && nbC1>=nbC2");
                int v = nbC1+ nbC2;
                if(v>valC2){
                    carafe_2.setValue(valC2);
                    carafe_2.setString(valC2+"Gallons");
                    int s= (nbC1+nbC2)-valC2;
                    carafe_1.setValue(s);
                    carafe_1.setString(s+"Gallons");
                }
                carafe_2.setValue(v);
                carafe_2.setString(v+"Gallons");
                int reste = valC2-(nbC1+nbC2);
                carafe_1.setValue(reste);
                carafe_1.setString(reste+"Gallon");
                
            }
            else{
            JOptionPane.showMessageDialog(null, "else");
            }
         
      }
      
      public void C2versC1(){
          icon_reussi.setVisible(false);
          txt_mvt2.setText("Transverser le contenu du Carafe N°2 vers N°1");
          txt_mvt1.setText("");
          valC1 = Integer.parseInt(nbEntrer_1.getText());
          valC2 = Integer.parseInt(nbEntrer_2.getText());
          int nbC1 = carafe_1.getValue();
          int nbC2 = carafe_2.getValue();
          //JOptionPane.showMessageDialog(this, "C1="+nbC1+"et"+"C2="+nbC2);
        
            if(nbC2==0){
              JOptionPane.showMessageDialog(null, "Opération non valide,carafe vide");
            }
            else if (nbC2>=valC1 && nbC1==0){
                carafe_1.setValue(valC1);
                carafe_1.setString(valC1 + "Gallons");
                nbC1=carafe_1.getValue();
                //JOptionPane.showMessageDialog(this, "C1="+nbC1+"et"+"C2="+nbC2);
                int s= nbC2 - valC1 ;
                carafe_2.setValue(s);
                
                carafe_2.setString(s+"Gallon");
            }
            else if(valC2>=valC1 && nbC1>0 && nbC1<=nbC2){
                //JOptionPane.showMessageDialog(null, "nbC1>0 && nbC1<=nbC2");
                carafe_1.setValue(nbC2+nbC1);
                carafe_1.setString(valC1+"Gallons");
                int s= valC2-(valC1-nbC1);
                carafe_2.setValue(s);
                carafe_2.setString(s+"Gallon(s)");
                nbC1 = carafe_1.getValue();
                //JOptionPane.showMessageDialog(this, "C1="+nbC1+"et"+"C2="+nbC2);
                }
            else if(valC2>=valC1 && nbC1==0 && valC1>=nbC2){
                //JOptionPane.showMessageDialog(null, "valC2>=valC1 && nbC1==0 && valC1>=nbC2");
                carafe_1.setValue(nbC2);
                carafe_1.setString(nbC2+"Gallons");
                int s= nbC2-valC1;
                carafe_2.setValue(s);
                carafe_2.setString(0+"Gallon");
                //JOptionPane.showMessageDialog(this, "C1="+nbC1+"et"+"C2="+nbC2);
                
            }
            else{
            JOptionPane.showMessageDialog(null, "erreur,opération non valide");
            }
      }
      private Timer createTimer ()
  {
    // Création d'une instance de listener 
    // associée au timer
    ActionListener action = new ActionListener ()
      {
        // Méthode appelée à chaque tic du timer
        public void actionPerformed (ActionEvent event)
        {
          // Si le premier pichet devient vide, remplissez-le
            int Valcherche=Integer.parseInt(nb_result.getText());
            
            int nbC1 = carafe_1.getValue();
            int nbC2 = carafe_2.getValue();
            JOptionPane.showMessageDialog(null, "ETAT INITIALE <=> "+"C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallon");
            reussi.setVisible(true);
            reussi.setText("STEP : 1");
            txt_mvt1.setVisible(true);
            txt_mvt2.setVisible(true);
            remplirC1();//remplir 
            nbC1 = carafe_1.getValue();
            nbC2 = carafe_2.getValue();
            JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallon");
            
            
            txt_mvt2.setText("");
          if (carafe_1.getValue() == valC1  || carafe_2.getValue()==0)//carafe1=3gallons Carafe2=0gallon
        {
            C1versC2();
            nbC1 = carafe_1.getValue();
            nbC2 = carafe_2.getValue();
            JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallons");
            
            //affichage();
        }
         /* else if (carafe_1.getValue() == 3  || carafe_2.getValue()==3)
        {
            viderC1();
        }*/
           if  (carafe_1.getValue() == 0  && carafe_2.getValue()<=valC2)//carafe1=Ogallon Carafe2=0G/1G/2G/3G/4G
           {
               remplirC1();//C1=3gallons
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallons");
               C1versC2();//C1=2Gallons et C2=4gallons
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallons");
               
               JOptionPane.showMessageDialog(null, "Opération reussi Carafe N°1="+Valcherche+"Gallons");
               reussi.setText("Opération reussi Carafe N°1="+Valcherche+"Gallons");
               icon_reussi.setVisible(true);
                /*try {
                    this.wait(10);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.notifyAll();*/
               viderC2();
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallon");
               
               // affichage();
           }
           if (carafe_1.getValue()==Valcherche && carafe_2.getValue()==0)
           {
               viderC1();
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallon");
               reussi.setText("STEP : 2");
               
               remplirC2();
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallons");
               
              // affichage();
           }
           
           if (carafe_1.getValue()==0 && carafe_2.getValue()==valC2)//C1=0G C2= 4G
           {
               C2versC1();
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallon");
               
               viderC1();
               nbC1 = carafe_1.getValue();
               nbC2 = carafe_2.getValue();
               JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallon");
               
               if (carafe_1.getValue()==0&&carafe_2.getValue()==1)
               {
                   C2versC1();//C1=1G C2=0G
                   nbC1 = carafe_1.getValue();
                   nbC2 = carafe_2.getValue();
                   JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallon");
                   remplirC2();
                   nbC1 = carafe_1.getValue();
                   nbC2 = carafe_2.getValue();
                   JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallons");
                   
                   C2versC1();
                   //C1=3G C2=2G
                   nbC1 = carafe_1.getValue();
                   nbC2 = carafe_2.getValue();
                   JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallons");
               }
           }
           if (carafe_1.getValue() == valC1 && carafe_2.getValue() == Valcherche)
                {
                     //C1=3 C2=2
                    viderC1();
                    nbC1 = carafe_1.getValue();
                    nbC2 = carafe_2.getValue();
                    JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallon et "+"C2="+nbC2+"Gallons");
                    
                    C2versC1();
                    nbC1 = carafe_1.getValue();
                    nbC2 = carafe_2.getValue();
                    JOptionPane.showMessageDialog(null, "C1="+nbC1+"Gallons et "+"C2="+nbC2+"Gallon");
                    
                    reussi.setText("Opération reussi Carafe N°1="+Valcherche+"Gallons");
                    icon_reussi.setVisible(true);
                try {
                    this.wait();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                setVisible(false);
                }
          else
           {
             reussi.setEnabled(false);  
             JOptionPane.showMessageDialog(null, "il y a une erreur qlq part");
             affichage();
           }
        }
      };
      
    // Création d'un timer qui génère un tic
    // chaque 500 millième de seconde
    return new Timer (500, action);
  } 
      
      public void tailleC1(){
          valC1 = Integer.parseInt(nbEntrer_1.getText());
          carafe3_gallon.setText("="+valC1+"G");
          
          if (valC1==10){
            
            carafe_1.setBounds(160, 50, 90, 200);
          }
          else if (valC1==9){
            carafe_1.setBounds(160, 71, 90, 180);
          }
          else if (valC1==8){
            carafe_1.setBounds(160, 92, 90, 160);
          }
          else if (valC1==7){
            carafe_1.setBounds(160, 113, 90, 140);
          }
          else if (valC1==6){
            carafe_1.setBounds(160, 134, 90, 120);
          }
          else if (valC1==5){
            carafe_1.setBounds(160, 155, 90, 100);
          }
          else if (valC1==4){
            carafe_1.setBounds(160, 176, 90, 80);
          }
          else if (valC1==3){
            carafe_1.setBounds(160, 197, 90, 60);
          }
          else if (valC1==2){
            carafe_1.setBounds(160, 218, 90, 40);
          }
          else if (valC1==1){
            carafe_1.setBounds(160, 239, 90, 20);
          }
          
          else{
          JOptionPane.showMessageDialog(this, "verifier le nombre entrer!!");
          }
      }
      public void tailleC2(){
          valC2 = Integer.parseInt(nbEntrer_2.getText());
          carafe4_gallon.setText("="+valC2+"G");
          
          if (valC2==10){
            
            carafe_2.setBounds(550, 50, 90, 200);
          }
          else if (valC2==9){
            carafe_2.setBounds(550, 71, 90, 180);
          }
          else if (valC2==8){
            carafe_2.setBounds(550, 92, 90, 160);
          }
          else if (valC2==7){
            carafe_2.setBounds(550, 113, 90, 140);
          }
          else if (valC2==6){
            carafe_2.setBounds(550, 134, 90, 120);
          }
          else if (valC2==5){
            carafe_2.setBounds(550, 155, 90, 100);
          }
          else if (valC2==4){
            carafe_2.setBounds(550, 176, 90, 80);
          }
          else if (valC2==3){
            carafe_2.setBounds(550, 197, 90, 60);
          }
          else if (valC2==2){
            carafe_2.setBounds(550, 218, 90, 40);
          }
          else if (valC2==1){
            carafe_2.setBounds(550, 239, 90, 20);
          }
          
          else{
          JOptionPane.showMessageDialog(this, "ERREUR");
          }
      }

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Timer timer;

        if (nbEntrer_1.getText().equals("") && nbEntrer_2.getText().equals("") ||nb_result.getText()
            .equals(""))
        {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tout les champs S'il vous plait!!");
        }
        else {
            if( JOptionPane.showConfirmDialog(this, "Les données entrer sont-elles exacte?", "VERIFIER et CONFIRMER!",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            timer = createTimer ();
            timer.start ();

        }
           
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nbEntrer_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbEntrer_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbEntrer_2ActionPerformed

    private void nbEntrer_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbEntrer_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbEntrer_1ActionPerformed

    private void btn_t1vers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_t1vers2ActionPerformed
        C1versC2();
    }//GEN-LAST:event_btn_t1vers2ActionPerformed

    private void btn_T2vers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_T2vers1ActionPerformed
       C2versC1();
    }//GEN-LAST:event_btn_T2vers1ActionPerformed

    private void btn_remplir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remplir1ActionPerformed
        remplirC1();
    }//GEN-LAST:event_btn_remplir1ActionPerformed

    private void btn_remplir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remplir2ActionPerformed
        remplirC2();
    }//GEN-LAST:event_btn_remplir2ActionPerformed

    private void btn_Vider2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Vider2ActionPerformed
        viderC2();
    }//GEN-LAST:event_btn_Vider2ActionPerformed

    private void btn_Vider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Vider1ActionPerformed
        viderC1();
    }//GEN-LAST:event_btn_Vider1ActionPerformed

    private void btn_tailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tailleActionPerformed
        
        tailleC1();
        tailleC2();
    }//GEN-LAST:event_btn_tailleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_T2vers1;
    private javax.swing.JButton btn_Vider1;
    private javax.swing.JButton btn_Vider2;
    private javax.swing.JButton btn_remplir1;
    private javax.swing.JButton btn_remplir2;
    private javax.swing.JButton btn_t1vers2;
    private javax.swing.JToggleButton btn_taille;
    private static javax.swing.JTextField carafe3_gallon;
    private static javax.swing.JTextField carafe4_gallon;
    private static javax.swing.JProgressBar carafe_1;
    private static javax.swing.JProgressBar carafe_2;
    private javax.swing.JLabel icon_reussi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField nbEntrer_1;
    private static javax.swing.JTextField nbEntrer_2;
    private static javax.swing.JTextField nb_result;
    private javax.swing.JLabel reussi;
    private javax.swing.JLabel txt_mvt1;
    private javax.swing.JLabel txt_mvt2;
    // End of variables declaration//GEN-END:variables
}
